version: 2
jobs:
  build:
    working_directory: ~/webblog
    docker:
      - image: circleci/python:3.6.4
    steps:
      - checkout
      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run: python3 -m venv venv
      - run:
          command: |
            . venv/bin/activate
            make local_requirements
      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - "venv"
      - run:
          name: Running tests
          command: |
            . venv/bin/activate
            make validate
      - store_artifacts:
          path: test-reports/
          destination: python_app
